# Generated by Django 6.0.1 on 2026-02-01 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_category_film_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
    ]
