# Generated by Django 6.0.1 on 2026-02-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_remove_film_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
