# Generated by Django 6.0.1 on 2026-02-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_category_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
