# Generated by Django 6.0.1 on 2026-02-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_alter_film_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
