# Generated by Django 6.0.1 on 2026-02-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_remove_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='films.genre'),
        ),
    ]
